### ISSUE TITLE
The editor has encountered an unexpected error.

### ISSUE THREAD

**Issue by iedev1** [advanced-bootstrap-blocks/advanced-bootstrap-blocks#5]
Good day

This is an awesome initiative and I would love to use this plugin. Unfortunately I'm running into some issues when trying to use it.

**Important info:**

- WordPress: Version 5.5.1
- Advanced Bootstrap Blocks: Version 1.5 (was on the last 1.4 version as well)
- Theme: Twenty Twenty
- Used Roots/Bedrock for WP setup
- Other plugins? I disabled all plugins and still get the errors.
- Using Gutenberg editor? Yes (Tried without it but I assume this is built for use with Gutenberg?)

**The error:**
When I try to add any "Advanced bootstrap blocks" blocks (Tried "Row" and "Card") via the editor I get an error popup with the following message:

`The editor has encountered an unexpected error.` with three buttons:

- Attempt Recovery
- Copy Post Text
- Copy Error

Clicking "Copy Error" gives the following:

```
TypeError: Cannot assign to read only property 'className' of object '#<Object>'
    at ModifyBlockListBlockCard(ModifyBlockListBlockButtonGroup(ModifyBlockListBlockColumn(ModifyBlockListBlockRow(ModifyBlockListBlockContainer(ModifyBlockListBlockContainer(WithFontSizeInlineStyles(((block_BlockListBlock))))))))) (/advanced-bootstrap-blocks/dist/blocks.build.js:1:107185)
    at renderWithHooks /wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:15246:18)
    at mountIndeterminateComponent (/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:17480:13)
    at beginWork$1 (/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:18624:16)
    at HTMLUnknownElement.callCallback (/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:341:14)
    at Object.invokeGuardedCallbackDev (/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:391:16)
    at invokeGuardedCallback (/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:448:31)
    at beginWork$$1 (/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:23355:7)
    at performUnitOfWork (/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:22349:12)
    at workLoopSync (/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:22323:22)
```

additionally in the JS console there is this:

```
The above error occurred in the <ModifyBlockListBlockCard(ModifyBlockListBlockButtonGroup(ModifyBlockListBlockColumn(ModifyBlockListBlockRow(ModifyBlockListBlockContainer(ModifyBlockListBlockContainer(WithFontSizeInlineStyles(((block_BlockListBlock)))))))))> component:
    in ModifyBlockListBlockCard(ModifyBlockListBlockButtonGroup(ModifyBlockListBlockColumn(ModifyBlockListBlockRow(ModifyBlockListBlockContainer(ModifyBlockListBlockContainer(WithFontSizeInlineStyles(((block_BlockListBlock))))))))) (created by ModifyBlockListBlockCardHeader(ModifyBlockListBlockCard(ModifyBlockListBlockButtonGroup(ModifyBlockListBlockColumn(ModifyBlockListBlockRow(ModifyBlockListBlockContainer(ModifyBlockListBlockContainer(WithFontSizeInlineStyles(((block_BlockListBlock)))))))))))
    in ModifyBlockListBlockCardHeader(ModifyBlockListBlockCard(ModifyBlockListBlockButtonGroup(ModifyBlockListBlockColumn(ModifyBlockListBlockRow(ModifyBlockListBlockContainer(ModifyBlockListBlockContainer(WithFontSizeInlineStyles(((block_BlockListBlock)))))))))) (created by ModifyBlockListBlockCardBody(ModifyBlockListBlockCardHeader(ModifyBlockListBlockCard(ModifyBlockListBlockButtonGroup(ModifyBlockListBlockColumn(ModifyBlockListBlockRow(ModifyBlockListBlockContainer(ModifyBlockListBlockContainer(WithFontSizeInlineStyles(((block_BlockListBlock))))))))))))
    in ModifyBlockListBlockCardBody(ModifyBlockListBlockCardHeader(ModifyBlockListBlockCard(ModifyBlockListBlockButtonGroup(ModifyBlockListBlockColumn(ModifyBlockListBlockRow(ModifyBlockListBlockContainer(ModifyBlockListBlockContainer(WithFontSizeInlineStyles(((block_BlockListBlock))))))))))) (created by ModifyBlockListBlockCardFooter(ModifyBlockListBlockCardBody(ModifyBlockListBlockCardHeader(ModifyBlockListBlockCard(ModifyBlockListBlockButtonGroup(ModifyBlockListBlockColumn(ModifyBlockListBlockRow(ModifyBlockListBlockContainer(ModifyBlockListBlockContainer(WithFontSizeInlineStyles(((block_BlockListBlock)))))))))))))
    in ModifyBlockListBlockCardFooter(ModifyBlockListBlockCardBody(ModifyBlockListBlockCardHeader(ModifyBlockListBlockCard(ModifyBlockListBlockButtonGroup(ModifyBlockListBlockColumn(ModifyBlockListBlockRow(ModifyBlockListBlockContainer(ModifyBlockListBlockContainer(WithFontSizeInlineStyles(((block_BlockListBlock)))))))))))) (created by ModifyBlockListBlockRow(ModifyBlockListBlockCardFooter(ModifyBlockListBlockCardBody(ModifyBlockListBlockCardHeader(ModifyBlockListBlockCard(ModifyBlockListBlockButtonGroup(ModifyBlockListBlockColumn(ModifyBlockListBlockRow(ModifyBlockListBlockContainer(ModifyBlockListBlockContainer(WithFontSizeInlineStyles(((block_BlockListBlock))))))))))))))
    in ModifyBlockListBlockRow(ModifyBlockListBlockCardFooter(ModifyBlockListBlockCardBody(ModifyBlockListBlockCardHeader(ModifyBlockListBlockCard(ModifyBlockListBlockButtonGroup(ModifyBlockListBlockColumn(ModifyBlockListBlockRow(ModifyBlockListBlockContainer(ModifyBlockListBlockContainer(WithFontSizeInlineStyles(((block_BlockListBlock))))))))))))) (created by WithFilters(block_BlockListBlock))
    in WithFilters(block_BlockListBlock) (created by IfCondition(WithFilters(block_BlockListBlock)))
```

or

```
TypeError: onCopy is not a function    /wp-includes/js/dist/components.js?ver=fbd4a5bf5809c79c6eef4817c6cbe9ea:28612:7   
```

**Additional errors:**

After clicking inside a editable area the following error is generated in the JS console:

```
react.js?ver=16.9.0:260 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `CustomMarginInspector(CustomPaddingInspector(CustomColumnInspector(WithMultipleValidation(WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit))))))))`. See https://fb.me/react-warning-keys for more information.
    in PanelRow (created by CustomMarginInspector(CustomPaddingInspector(CustomColumnInspector(WithMultipleValidation(WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit)))))))))
    in CustomMarginInspector(CustomPaddingInspector(CustomColumnInspector(WithMultipleValidation(WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Edit)))))))) 
```

Let me know if you need any more info?

Any help would be appreciated.

Apologies if I'm using it wrong!

Regards

**Comment by shrthnd** [comment]
Thank you for you for submitting this issue, @iedev1!

I am not able to recreate the problem (in Firefox, Chrome, and Safari) in a fresh installation of WordPress running ABB v1.5. But, I don't think you're using it wrong and hope we can get this patched up. Certainly it is good to know the [onCopy bug](https://wordpress.org/support/topic/typeerror-oncopy-is-not-a-function/) reported earlier was not a fluke.

Based on the console output you've shared I may have resolved an issue or two in the code which could lead to the unexpected error. (Specifically: add missing _key_ assignments to mapped values inside the padding/margin inspectors, and correct a type-error in an attribute of the cardHeader template.)

If/when you are able to give this another go, [v1.6 is ready for review](https://downloads.wordpress.org/plugin/advanced-bootstrap-blocks.1.6.zip). Please let me know if the situation improves and thanks again for your input!

**Comment by iedev1** [comment]
Thanks for getting back to me.

I installed v1.6 and tested it. Based on the linked issue I'll add some more info:

**What web browser and operating system are you using?** 
I'm using MacOS Catalina. Primarily Chrome for dev.
**Does this occur in all web browsers?**
I tested in Safari, Chrome, and Firefox and the issue is present in all of them.
**Do you have any browser extensions installed?**
To isolate the issue I tested in incognito/private mode and the issue still persists.

With version 1.6 the `The editor has encountered an unexpected error.` popup is still present with the following error:
`Uncaught TypeError: "className" is read-only` in the `plugins/advanced-bootstrap-blocks/dist/blocks.build.js` or `blocks.build.js:1 Uncaught TypeError: Cannot assign to read only property 'className' of object`

Good news though, both the "onCopy" issue as well as the "Each child in a list should have a unique 'key' prop" issue have been resolved.

I have also tested version 1.6 on a completely new WordPress (5.5.1) installation. Basic TwentyTwenty theme with no other plugins or customisations.

Let me know if there is anything else I can do to help narrow this down.

**Comment by shrthnd** [comment]
> Good news though, both the "onCopy" issue as well as the "Each child in a list should have a unique 'key' prop" issue have been resolved.

Indeed! Thank you for sharing

> With version 1.6 the `The editor has encountered an unexpected error.` popup is still present with the following error:
`Uncaught TypeError: "className" is read-only in the plugins/advanced-bootstrap-blocks/dist/blocks.build.js or blocks.build.js:1 Uncaught TypeError: Cannot assign to read only property 'className' of object`

The changes in [this commit](https://github.com/advanced-bootstrap-blocks/advanced-bootstrap-blocks/commit/de62f74f00e4ffb779a6bc4572697d908eace2d2) might fix the read-only property issue? 

> Let me know if there is anything else I can do to help narrow this down.

If you don't mind testing again, here is a [direct link to the download](https://github.com/advanced-bootstrap-blocks/advanced-bootstrap-blocks/archive/bugfix/unexpected-error.zip). After reinstalling, you may want to clear your browser cache (or open the dev tools and reload the page.) 

Let me know if this helps. If not, would you consider testing in a non-Bedrock WordPress installation? Otherwise, I'll need to figure out how to reproduce the issue on my end to continue debugging.

Thanks again for testing and reporting these issues.

**Comment by iedev1** [comment]
Excellent! That fix seemed to do the trick. I could successfully add various elements and no errors.

Thank you so much for the effort and the great work!

**Comment by shrthnd** [comment]
Happy to help! Your feedback was critical here, @iedev1. Let me know if you run into any other issues.
